### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by shmuelr** [shmuelr/touro-mco152#4]
Just a reminder to everyone to make sure your local branch is up-to-date before working on the project. Otherwise you won't be able to commit from your local branch to the remote branch.

**Comment by shmuelr** [comment]
1 Git Pull
2 Make sure your branch is checked out locally (has the little check box on it)
3 Hard-Reset on the remote master
4 Push local branch (overwrite remote copy)
5 Work on your local branch

**Comment by reuvainsilverman** [comment]
how do you check if your branch is up to date on github?

**Comment by shmuelr** [comment]
In the Git workspace view make sure the last commit is the most current one.
Or you can look online at the graph view for the project.

**Comment by eytansterling** [comment]
When did we agree to finish chapter 5 by?

On Thu, Mar 19, 2015 at 11:41 PM, shmuelr <notifications@github.com> wrote:

> Closed #4 <https://github.com/shmuelr/touro-mco152/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shmuelr/touro-mco152/issues/4#event-260110398>.
>



-- 
*Eytan Sterling*
*simchatorah.blogspot.com <http://simchatorah.blogspot.com>*
