### ISSUE TITLE
Counter for black and white pieces total

### ISSUE THREAD

**Issue by reuvainsilverman** [shmuelr/touro-mco152#5]
I made 2 counters to track the total number of blacks pieces and whites pieces in the Piece Class as the book said. However, I noticed that if you set up the board twice or create two board objects, it makes the totals for the two counters into 32. Did anyone else get this problem or did you guys do it differently?

**Comment by maric1** [comment]
Maybe because you forgot to reset the variable you use for the counter.

**Comment by shmuelr** [comment]
Are you using statics anywhere?
