### ISSUE TITLE
My Reset isn't working

### ISSUE THREAD

**Issue by reuvainsilverman** [shmuelr/touro-mco152#8]
I am trying to reset my branch and my master branch on eclipse and it isn't working correctly. It gets the newest code, but it isn't removing/overwriting my old code.

**Comment by shmuelr** [comment]
you have to run a 'Hard' reset. this wipes your old code

**Comment by reuvainsilverman** [comment]
I did that.

**Comment by maric1** [comment]
I think you have to choose 'rebase' and then choose overwrite any diverging
code.

**Comment by reuvainsilverman** [comment]
I did not.

**Comment by reuvainsilverman** [comment]
Sorry misread your comment. What do you mean?

**Comment by maric1** [comment]
in the git view, right-click on your branch and choose 'rebase', then
select the master. In the dialog, there is going to be an option to delete
any all your previous code, check it.

**Comment by reuvainsilverman** [comment]
I just tried rebasing on the master and I got the following message: "Rebase did nothing, HEAD was already up to date"

**Comment by maric1** [comment]
Do you want me to try to do it for you?

**Comment by reuvainsilverman** [comment]
sure

**Comment by shmuelr** [comment]
Btw, worst case you can delete the project in eclipse and just set it up
again. All the code is in the cloud.

**Comment by reuvainsilverman** [comment]
Should I just do that?

**Comment by maric1** [comment]
Can I log into your pc over team viewer?

**Comment by reuvainsilverman** [comment]
yeah

**Comment by maric1** [comment]
Ok, what's your id(you can send it privately, if you want)

**Comment by reuvainsilverman** [comment]
I did.
